name: Build, Test, and Deploy PULCEO Documentation

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      mdbook_site_url:
        required: true
        type: string
      folder:
        required: true
        type: string
      target_folder:
        required: true
        type: string
      clean_exclude:
        required: true
        type: string

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo '' >> book.toml
          echo '[output.html]' >> book.toml
          echo 'site-url = "${{ inputs.mdbook_site_url }}"' >> book.toml
      - uses: actions/cache@v3
        id: cache-mdbook-binary
        with:
          path: ./mdbook/
          key: ${{ runner.os }}-${{ hashFiles('**/MDBOOK_VERSION') }}
      - run: cat MDBOOK_VERSION >> $GITHUB_ENV
      - run: |
          mkdir mdbook
          curl -Lf https://github.com/rust-lang/mdBook/releases/download/${{ env.MDBOOK_VERSION }}/mdbook-${{ env.MDBOOK_VERSION }}-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=./mdbook
        if: steps.cache-mdbook-binary.outputs.cache-hit != 'true'
      - run: echo ./mdbook >> $GITHUB_PATH
      - run: mkdir ${{ inputs.folder }}
      - run: mdbook build -d ${{ inputs.folder }}
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: ${{ inputs.folder }}
          force: false
          target-folder: ${{ inputs.target_folder }}
          clean-exclude: ${{ inputs.clean_exclude }}